import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="bg-black text-white py-4">
      <div className="container px-28 mx-auto">
        <nav className="flex justify-between items-center">
          <Link href="/">
            <h1 className="text-2xl hover:text-blue-500 transition-colors duration-300 cursor-pointer font-bold ">Hackathon Frontend</h1>
          </Link>
          <div className="flex gap-5 items-center">
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/newEquipe"
            >
              Cadastrar Equipe
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/equipes"
            >
              Equipes
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/newAvaliador"
            >
              Cadastrar Avaliador
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/avaliadores"
            >
              Avaliadores
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/newAvaliacao"
            >
              Cadastrar Avaliação
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/avaliacoes"
            >
              Avaliações
            </Link>
            <Link
              className="text-white hover:text-blue-500 transition-colors duration-300 cursor-pointer"
              href="/logout"
            >
              Entrar
            </Link>
          </div>
        </nav>
      </div>
    </header>
  );
};

// Componente de rodapé
const Footer = () => {
  return (
    <footer className="bg-black text-white py-4 fixed bottom-0 w-full">
      <div className="container px-28 mx-auto">Code Race, 2023. Todos os direitos reservados.</div>
    </footer>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex flex-col min-h-screen">
          <div className="container px-24 mx-auto">
            {children}
          </div>
        <Footer />
        </div>
      </body>
    </html>
  );
}
